CREATE SCHEMA IF NOT EXISTS flomaro;
REVOKE ALL ON SCHEMA flomaro FROM PUBLIC;
SET search_path TO flomaro, pg_catalog;

        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name TEXT NOT NULL,
            last_name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            phone TEXT NOT NULL,
            pin_hash TEXT NOT NULL,
            access_level TEXT NOT NULL DEFAULT 'employee',
            hourly_rate DOUBLE PRECISION NOT NULL DEFAULT 32,
            active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS')
        );

        CREATE TABLE IF NOT EXISTS registration_requests (
            token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS work_groups (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS user_work_groups (
            user_id INTEGER NOT NULL,
            group_id INTEGER NOT NULL,
            PRIMARY KEY (user_id, group_id),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (group_id) REFERENCES work_groups(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS schedules (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            work_date TEXT NOT NULL,
            start_time TEXT NOT NULL,
            end_time TEXT NOT NULL,
            note TEXT,
            work_group TEXT,
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS'),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS events (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            event_date TEXT NOT NULL,
            start_time TEXT NOT NULL,
            end_time TEXT NOT NULL,
            location TEXT,
            note TEXT,
            manager_id INTEGER,
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS'),
            FOREIGN KEY (manager_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS event_assignments (
            event_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            PRIMARY KEY (event_id, user_id),
            FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS event_attachments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            content BYTEA NOT NULL,
            sha256 TEXT NOT NULL,
            uploaded_by INTEGER NOT NULL REFERENCES users(id),
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS'),
            UNIQUE(event_id, sha256)
        );

        CREATE TABLE IF NOT EXISTS payments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            period_from TEXT NOT NULL,
            period_to TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            status TEXT NOT NULL DEFAULT 'created',
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS'),
            sent_at TEXT,
            received_at TEXT,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );


        CREATE TABLE IF NOT EXISTS availabilities (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            availability_date TEXT NOT NULL,
            availability_type TEXT NOT NULL,
            start_time TEXT,
            end_time TEXT,
            note TEXT,
            updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS'),
            UNIQUE(user_id, availability_date),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            notification_type TEXT NOT NULL DEFAULT 'info',
            title TEXT NOT NULL,
            message TEXT NOT NULL,
            is_read INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS'),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS shifts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            start_at TEXT NOT NULL,
            end_at TEXT,
            actual_minutes INTEGER,
            billable_hours INTEGER,
            hourly_rate DOUBLE PRECISION,
            amount DOUBLE PRECISION,
            approval_status TEXT NOT NULL DEFAULT 'active',
            approved_by INTEGER,
            approved_at TEXT,
            payment_id INTEGER,
            original_start_at TEXT,
            original_end_at TEXT,
            corrected_by INTEGER,
            corrected_at TEXT,
            correction_note TEXT,
            rejection_note TEXT,
            work_group TEXT,
            created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD HH24:MI:SS'),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (approved_by) REFERENCES users(id),
            FOREIGN KEY (corrected_by) REFERENCES users(id),
            FOREIGN KEY (payment_id) REFERENCES payments(id)
        );
        
REVOKE ALL ON ALL TABLES IN SCHEMA flomaro FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA flomaro FROM PUBLIC;
